# Generated by Django 5.2.7 on 2025-10-27 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('place', models.CharField(help_text="Место выполнения привычки (например, 'дом')", max_length=255)),
                ('time', models.TimeField(help_text='Время выполнения (например, 07:00)')),
                ('action', models.CharField(help_text="Действие привычки (например, 'выпить стакан воды')", max_length=255)),
                ('is_pleasant', models.BooleanField(default=False, help_text='Приятная привычка (без вознаграждения)')),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Частота выполнения')),
                ('frequency_unit', models.CharField(choices=[('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')], default='days', help_text='Единица измерения частоты', max_length=10)),
                ('reward', models.CharField(blank=True, help_text='Вознаграждение после выполнения', max_length=255, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Время на выполнение в секундах (<=120)')),
                ('is_public', models.BooleanField(default=False, help_text='Публичная привычка (другие могут видеть)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('related_habit', models.ForeignKey(blank=True, help_text='Связанная приятная привычка (альтернатива вознаграждению)', limit_choices_to={'is_pleasant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_from', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
