# Generated by Django 5.2.7 on 2025-10-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at']},
        ),
    ]
