# Generated by Django 5.2.7 on 2025-10-24 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='action',
            field=models.CharField(default='', help_text="Действие привычки (например, 'выпить стакан воды')", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Время на выполнение в секундах (<=120)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, help_text='Приятная привычка (без вознаграждения)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Публичная привычка (другие могут видеть)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='place',
            field=models.CharField(default='', help_text="Место выполнения привычки (например, 'дом')", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Связанная приятная привычка (альтернатива вознаграждению)', limit_choices_to={'is_pleasant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, help_text='Вознаграждение после выполнения', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.TimeField(default='07:00', help_text='Время выполнения (например, 07:00)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveIntegerField(default=1, help_text='Частота выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency_unit',
            field=models.CharField(choices=[('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')], default='days', help_text='Единица измерения частоты', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('user', 'name')},
        ),
    ]
