# Generated by Django 5.2.7 on 2025-10-25 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_action_habit_duration_habit_is_pleasant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Связанная приятная привычка (альтернатива вознаграждению)', limit_choices_to={'is_pleasant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_from', to='habits.habit'),
        ),
    ]
